package Bai2;

public class Java {
    public  static  void  main(String[] args) {
        String fullName = "Nguyễn Văn A";
        int age = 23;
        String study = "PTIT-HCM";
        String address = "Cà Mau";

        System.out.println("Tên:" + fullName);
        System.out.println("Tuổi:" + age);
        System.out.println("Hiện tại đang học tại:" +study);
        System.out.println("Quê quán:" + address);
    }
}
