package Bai3;

public class Java {
    public  static  void  main(String[] args) {
//        Bán kính 1
        double radius1 = 1;
        double area1 = 3.14;
        System.out.println("Bán kính:" + radius1 + " Diện tích:" + area1);
//        Bán kính 3
        double radius3 = 3;
        double area3 = 3.14 * radius3 * radius3;
        System.out.println("Bán kính:" + radius3 + " Diện tích:" + area3);
//        Bán kính 5
        double radius5 = 5;
        double area5 = 3.14 * radius5 *radius5;
        System.out.println("Bán kính:" + radius5 + " Diện tích:" + area5);
//        Bán kính 0
        double radius0 = 0;
        double area0 = 3.14 * radius0;
        System.out.println("Bán kính:" + radius0 + " Diện tích:" + area0);
//        Bán kính 10
        double radius10 = 10;
        double area10 = 3.14 * radius10 * radius10;
        System.out.println("Bán kính:" + radius10 + " Diện tích:" + area10);
    }
}
