package Bai4;

public class Java {
    public  static  void  main(String[] args) {
//        Khai báo và gán giá trị
        int a = 10;
        int b = 5;
//        Thực hiện các phép tính
        int total = a + b;
        int numberSign = a - b; // số hiệu
        int accumulation = a * b;
        int numberQuotient = a / b; // số thương
        int residual = a % b; // phần dư
//        Kết quả
        System.out.println(total);
        System.out.println(numberSign);
        System.out.println(accumulation);
        System.out.println(numberQuotient);
        System.out.println(residual);
    }
}
